// "Trust & Clarity" palette — white surfaces with a royal-blue / deep-navy
// brand pair, plus a sky-blue accent for secondary/informational states.
const palette = {
  royalLight: '#155EEF',
  royalDark: '#4C8DFF',
};

export default {
  light: {
    text: '#0B1220',
    textMuted: '#67728A',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceSunken: '#F1F5FB',
    tint: palette.royalLight,
    tabIconDefault: '#9AA5B8',
    tabIconSelected: palette.royalLight,
    primary: palette.royalLight,
    primarySoft: '#E3ECFF',
    secondary: '#0B1E3D',
    secondarySoft: '#E7ECF5',
    accentSky: '#0EA5E9',
    accentSkySoft: '#E0F2FE',
    heroAccent: '#8FC1FF',
    success: '#1D9A6C',
    successSoft: '#E4F6EE',
    danger: '#DC3545',
    dangerSoft: '#FBE4E6',
    border: '#E3E8F2',
    borderStrong: '#C7D2E3',
    card: '#FFFFFF',
    overlay: 'rgba(11, 18, 32, 0.55)',
  },
  dark: {
    text: '#EAF0FB',
    textMuted: '#8B96AC',
    background: '#0A1220',
    surface: '#101B30',
    surfaceSunken: '#152238',
    tint: palette.royalDark,
    tabIconDefault: '#57647E',
    tabIconSelected: palette.royalDark,
    primary: palette.royalDark,
    primarySoft: '#16294D',
    secondary: '#13294F',
    secondarySoft: '#152A4A',
    accentSky: '#38BDF8',
    accentSkySoft: '#123247',
    heroAccent: '#8FC1FF',
    success: '#34C77B',
    successSoft: '#0F3324',
    danger: '#F0655A',
    dangerSoft: '#3A1E1F',
    border: '#1D2A45',
    borderStrong: '#2B3A5C',
    card: '#101B30',
    overlay: 'rgba(0, 0, 0, 0.65)',
  },
};
