// "Santé Fraîche" palette — client-provided redesign: every screen sits on a
// teal -> green diagonal gradient, with white cards/fields floating on top.
const palette = {
  tealLight: '#19A9B1',
  tealDark: '#0E7A80',
  greenLight: '#87C443',
  greenDark: '#5F9A2A',
};

export default {
  light: {
    text: '#0B1220',
    textMuted: '#67728A',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceSunken: '#F1F5FB',
    tint: palette.tealLight,
    tabIconDefault: 'rgba(255, 255, 255, 0.75)',
    tabIconSelected: '#FFFFFF',
    primary: palette.tealLight,
    primarySoft: '#E1F4F5',
    secondary: palette.greenDark,
    secondarySoft: '#EFF7E4',
    accentSky: '#0EA5E9',
    accentSkySoft: '#E0F2FE',
    heroAccent: '#8FC1FF',
    // Direct-on-gradient text (page titles/subtitles). Card-internal text
    // keeps using `text`/`textMuted` above since cards stay white.
    heading: '#FFFFFF',
    headingMuted: 'rgba(255, 255, 255, 0.85)',
    gradientStart: palette.tealLight,
    gradientEnd: palette.greenLight,
    success: palette.greenDark,
    successSoft: '#EAF6DA',
    danger: '#DC3545',
    dangerSoft: '#FBE4E6',
    border: '#E3E8F2',
    borderStrong: '#C7D2E3',
    card: '#FFFFFF',
    overlay: 'rgba(11, 18, 32, 0.55)',
  },
  dark: {
    text: '#EAF0FB',
    textMuted: '#8B96AC',
    background: '#0A1220',
    surface: '#101B30',
    surfaceSunken: '#152238',
    tint: palette.tealLight,
    tabIconDefault: '#57647E',
    tabIconSelected: palette.tealLight,
    primary: palette.tealLight,
    primarySoft: '#16294D',
    secondary: palette.greenDark,
    secondarySoft: '#152A4A',
    accentSky: '#38BDF8',
    accentSkySoft: '#123247',
    heroAccent: '#8FC1FF',
    heading: '#EAF0FB',
    headingMuted: '#8B96AC',
    gradientStart: '#0A1220',
    gradientEnd: '#0A1220',
    success: '#34C77B',
    successSoft: '#0F3324',
    danger: '#F0655A',
    dangerSoft: '#3A1E1F',
    border: '#1D2A45',
    borderStrong: '#2B3A5C',
    card: '#101B30',
    overlay: 'rgba(0, 0, 0, 0.65)',
  },
};
